name: brew test-bot

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: 'Ref to checkout'
        required: true
        type: string
  push:
    branches:
      - main
  pull_request:
    types: [ "opened", "reopened", "synchronize", "ready_for_review" ]
    branches: [ "main" ]

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        if: github.event_name == 'workflow_call'
        with:
          ref: ${{ github.event.inputs.checkout_ref }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: |
           brew test-bot --only-cleanup-before | tee brew_test_log.txt
           if grep -q "Warning: 1 failed step ignored!" brew_test_log.txt; then
             echo "Test failed. Exiting with failure."
             exit 1
           fi

      - run: |
           brew test-bot --only-setup | tee brew_test_log.txt
           if grep -q "Warning: 1 failed step ignored!" brew_test_log.txt; then
             echo "Test failed. Exiting with failure."
             exit 1
           fi

      - run: |
           brew test-bot --only-tap-syntax | tee brew_test_log.txt
           
      - run: |
           brew test-bot --only-formulae | tee brew_test_log.txt
           if grep -q "Warning: 1 failed step ignored!" brew_test_log.txt; then
             echo "Test failed. Exiting with failure."
             exit 1
           fi
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_call'

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_call'
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
