name: brew test-bot

on:
  push:
    branches:
      - main
  pull_request:
    types: [ labeled ]

jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - run: |
           brew test-bot --only-cleanup-before | tee brew_test_log.txt
           if grep -q "Warning: 1 failed step ignored!" brew_test_log.txt; then
             echo "Test failed. Exiting with failure."
             exit 1
           fi

      - run: |
           brew test-bot --only-setup | tee brew_test_log.txt
           if grep -q "Warning: 1 failed step ignored!" brew_test_log.txt; then
             echo "Test failed. Exiting with failure."
             exit 1
           fi

      - run: |
           brew test-bot --only-tap-syntax | tee brew_test_log.txt
           if grep -q "Warning: 1 failed step ignored!" brew_test_log.txt; then
             echo "Test failed. Exiting with failure."
             exit 1
           fi

      - run: |
           brew test-bot --only-formulae | tee brew_test_log.txt
           if grep -q "Warning: 1 failed step ignored!" brew_test_log.txt; then
             echo "Test failed. Exiting with failure."
             exit 1
           fi
        if: github.event_name == 'pull_request'

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: bottles_${{ matrix.os }}
          path: '*.bottle.*'
