name: Update Homebrew Formula

on:
    release:
      types: [created]
    workflow_call:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Release Info
        id: release
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Get SHA256 Checksum
        run: |
          ASSET_URL_DARWIN_X86=$(curl -s https://github.com/MirantisContainers/mke-release/releases/download/${{ env.version }}/mkectl_darwin_x86_64.tar.gz)
          ASSET_URL_DARWIN_ARM64=$(curl -s https://github.com/MirantisContainers/mke-release/releases/download/${{ env.version }}/mkectl_darwin_arm64.tar.gz)
          ASSET_URL_LINUX_X86=$(curl -s https://github.com/MirantisContainers/mke-release/releases/download/${{ env.version }}/mkectl_linux_x86_64.tar.gz)
          ASSET_URL_LINUX_ARM64=$(curl -s https://github.com/MirantisContainers/mke-release/releases/download/${{ env.version }}/mkectl_linux_arm64.zip)

          curl -L -o mkectl_darwin_x86_64.tar.gz "$ASSET_URL_DARWIN_X86"
          echo "sha256_darwin_x86=$(sha256sum mkectl_darwin_x86_64.tar.gz | awk '{print $1}')" >> $GITHUB_ENV
          
          curl -L -o mkectl_darwin_arm64.tar.gz "ASSET_URL_DARWIN_ARM64"
          echo "sha256_darwin_arm64=$(sha256sum mkectl_darwin_arm64.tar.gz | awk '{print $1}')" >> $GITHUB_ENV
          
          curl -L -o mkectl_linux_x86_64.tar.gz "ASSET_URL_LINUX_X86"
          echo "sha256_linux_x86=$(sha256sum mkectl_linux_x86_64.tar.gz | awk '{print $1}')" >> $GITHUB_ENV
          
          curl -L -o mkectl_linux_arm64.tar.gz "ASSET_URL_LINUX_ARM64"
          echo "sha256_linux_arm64=$(sha256sum mkectl_linux_arm64.tar.gz | awk '{print $1}')" >> $GITHUB_ENV

      - name: Update Homebrew Formula
        run: |
          FORMULA_PATH="Formula/mkectl.rb"
          sed -i -e "s/VERSION = \".*\"/VERSION = \"${{ env.version }}\"/" \
                 -e "0,/sha256 \".*\"/s//sha256 \"${{ env.sha256_darwin_x86 }}\"/" \
                 -e "1,/sha256 \".*\"/s//sha256 \"${{ env.sha256_darwin_arm64 }}\"/" \
                 -e "2,/sha256 \".*\"/s//sha256 \"${{ env.sha256_linux_x86 }}\"/" \
                 -e "3,/sha256 \".*\"/s//sha256 \"${{ env.sha256_linux_arm64 }}\"/" $FORMULA_PATH
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b update-mkectl-${{ env.version }}
          git add Formula/mkectl.rb
          git commit -m "Update mkectl to ${{ env.version }}"
          git push origin update-mkectl-${{ env.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Update mkectl formula to ${{ env.version }}"
          body: "This PR updates the mkectl formula to version ${{ env.version }}."
          branch: update-mkectl-${{ env.version }}
          base: main
